"""Nightly consolidation: read yesterday's logs, propose memory updates, apply tiering."""

from __future__ import annotations

import json
import re
from datetime import date, datetime, timedelta
from pathlib import Path

from buddy.config import get_settings
from buddy.db import get_session_factory
from buddy.llm.client import chat
from buddy.llm.models import ModelTier, resolve_model
from buddy.llm.prompts.consolidation import CONSOLIDATION_SYSTEM
from buddy.logging_setup import get_logger
from buddy.memory.dreams import stage_proposals
from buddy.memory.index import index_file
from buddy.memory.store import MemoryStore
from buddy.models import ApiUsage

log = get_logger("buddy.consolidation")


def _load_conversations_for(store: MemoryStore, day: date) -> str:
    folder = Path(store.root) / "conversations" / day.isoformat()
    if not folder.exists():
        return ""
    parts: list[str] = []
    for f in sorted(folder.glob("*.md")):
        parts.append(f"\n----- {f.name} -----\n")
        parts.append(f.read_text(encoding="utf-8"))
    return "\n".join(parts)


def _strip_fences(text: str) -> str:
    cleaned = text.strip()
    fence = re.match(r"^```(?:json)?\s*(.*?)\s*```$", cleaned, re.DOTALL)
    if fence:
        cleaned = fence.group(1)
    return cleaned


async def run_consolidation(*, for_date: date | None = None) -> dict:
    """Process the conversations for a given date (defaults to yesterday)."""
    settings = get_settings()
    store = MemoryStore()
    target = for_date or (datetime.now().date() - timedelta(days=1))

    convos = _load_conversations_for(store, target)
    if not convos.strip():
        log.info("consolidation.no_conversations", day=str(target))
        return {"day": str(target), "status": "no_conversations"}

    persona = store.read("PERSONA.md") if store.exists("PERSONA.md") else ""
    memory = store.read("MEMORY.md") if store.exists("MEMORY.md") else ""
    patterns = store.read("PATTERNS.md") if store.exists("PATTERNS.md") else ""

    user_payload = (
        f"Date: {target.isoformat()}\n\n"
        f"### PERSONA.md\n{persona}\n\n"
        f"### MEMORY.md\n{memory}\n\n"
        f"### PATTERNS.md\n{patterns}\n\n"
        f"### Conversations from {target.isoformat()}\n{convos}\n"
    )

    model = resolve_model(ModelTier.REASONING)
    last_err: Exception | None = None
    payload = None
    for attempt in range(2):
        try:
            result = await chat(
                model=model,
                system=CONSOLIDATION_SYSTEM,
                messages=[{"role": "user", "content": user_payload}],
                max_tokens=4096,
                temperature=0.3,
            )
            payload = json.loads(_strip_fences(result.text))
            break
        except (json.JSONDecodeError, Exception) as exc:  # noqa: BLE001
            last_err = exc
            log.warn("consolidation.parse_failed", attempt=attempt, error=str(exc))

    if payload is None:
        log.error("consolidation.failed", error=str(last_err))
        return {"day": str(target), "status": "failed", "error": str(last_err)}

    factory = get_session_factory()
    async with factory() as db:
        db.add(
            ApiUsage(
                provider="anthropic",
                model=result.model,
                operation="consolidation",
                tokens_in=result.tokens_in,
                tokens_out=result.tokens_out,
                cost_usd=result.cost_usd,
            )
        )
        await db.commit()

    # Day summary -> days/YYYY-MM-DD.md
    day_summary = (payload.get("day_summary") or "").strip()
    if day_summary:
        day_path = store.day_file_path(target.isoformat())
        body = (
            f"# {target.isoformat()}\n\n"
            f"_Generated by the consolidation pass on {datetime.utcnow().isoformat()}Z._\n\n"
            f"{day_summary}\n"
        )
        store.write(day_path, body, commit_message=f"consolidation: day summary {target}")
        await index_file(day_path, store=store)

    auto = payload.get("auto_apply") or []
    review = payload.get("review") or []
    counts = await stage_proposals(auto_apply_items=auto, review_items=review)

    log.info(
        "consolidation.complete",
        day=str(target),
        auto_applied=counts["auto_applied"],
        pending_review=counts["pending_review"],
    )

    # Best-effort backup push.
    try:
        store.push_to_remote()
    except Exception:  # noqa: BLE001
        pass

    return {
        "day": str(target),
        "status": "ok",
        "summary_written": bool(day_summary),
        **counts,
    }
