"""Conventions for the memory directory layout.

Phase 0 file inventory (per the spec):

    memory/
    ├── README.md               # Human-readable explanation
    ├── MEMORY.md               # Identity layer
    ├── PERSONA.md              # Persona profile
    ├── PATTERNS.md             # Observed patterns
    ├── DREAMS.md               # Pending review queue (mirrors DB)
    ├── days/YYYY-MM-DD.md      # Daily summary
    ├── episodes/<slug>.md      # Significant events
    └── conversations/YYYY-MM-DD/<session>.md
"""

from __future__ import annotations

from enum import Enum

# Files always loaded into the persona prompt at conversation time.
ALWAYS_LOADED_FILES: tuple[str, ...] = (
    "MEMORY.md",
    "PERSONA.md",
)

# These exist at the top level.
TOP_LEVEL_FILES: tuple[str, ...] = (
    "README.md",
    "MEMORY.md",
    "PERSONA.md",
    "PATTERNS.md",
    "DREAMS.md",
)


class DocumentType(str, Enum):
    IDENTITY = "identity"
    PERSONA = "persona"
    PATTERNS = "patterns"
    DREAMS = "dreams"
    DAY = "day"
    EPISODE = "episode"
    CONVERSATION = "conversation"
    README = "readme"
    OTHER = "other"


def classify_path(rel_path: str) -> DocumentType:
    p = rel_path.replace("\\", "/")
    if p == "MEMORY.md":
        return DocumentType.IDENTITY
    if p == "PERSONA.md":
        return DocumentType.PERSONA
    if p == "PATTERNS.md":
        return DocumentType.PATTERNS
    if p == "DREAMS.md":
        return DocumentType.DREAMS
    if p == "README.md":
        return DocumentType.README
    if p.startswith("days/"):
        return DocumentType.DAY
    if p.startswith("episodes/"):
        return DocumentType.EPISODE
    if p.startswith("conversations/"):
        return DocumentType.CONVERSATION
    return DocumentType.OTHER


# Initial seed contents for empty memory directory.
SEED_FILES: dict[str, str] = {
    "README.md": """# Buddy Memory

This directory is the source of truth for everything the system knows.
Every file is plain Markdown. Every change is a git commit.

## Structure

- `MEMORY.md`   — durable identity facts about you. Reviewed before silent edits.
- `PERSONA.md`  — the calibrated persona profile (built during onboarding).
- `PATTERNS.md` — observed patterns about how you work.
- `DREAMS.md`   — proposed memory updates awaiting your review.
- `days/`       — one summary file per day.
- `episodes/`   — significant events worth remembering specifically.
- `conversations/` — raw conversation logs (search-only by default).

## Editing

You can edit any file in this directory directly. The system will detect
the change on its next index pass (every 30 seconds during active use, and
always at conversation time).

## History

Every change is a git commit. `git log` to see the full timeline of what
the system has learned about you.
""",
    "MEMORY.md": """# About {user_name}

_This file is empty until the persona calibration intake runs._

The intake will populate this with:

- Profession and work context
- Cognitive profile
- Key relationships
- Location, timezone
- Stated values
- Communication preferences
- Current high-level goals

Until then, the persona will know only what you tell it in conversation.
""",
    "PERSONA.md": """# Persona Profile

_Run the intake to generate this file. Until then, the persona uses defaults._

## Name
{persona_name}

## Calibration Axes

### Warmth
neutral

### Directness
balanced

### Humor
dry

### Pace
measured

### Failure Register
matter-of-fact

### Pushback Tendency
calibrated

## Free-form Guidance

Default placeholder. Run `buddy intake` to replace this with your real profile.

## Sample Exchanges

_(Generated by intake.)_

## Behavioral Anchors

- Prefer short, dense responses to routine questions.
- Don't open with "I" or with sycophantic phrases.
- When in doubt about goals/values, ask. When in doubt about execution, recommend.
""",
    "PATTERNS.md": """# Patterns

_Patterns observed by the consolidation pass land here, organized by category._

## productive_hours

_(none yet)_

## task_stalls

_(none yet)_

## intervention_response

_(none yet)_

## energy

_(none yet)_
""",
    "DREAMS.md": """# Dreams

_Proposed memory updates awaiting review will appear here._

## REQUIRES REVIEW

_(none)_

## AUTO-APPLIED (for your awareness)

_(none yet)_
""",
}
